/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    Account: typeof import('./../layout/headerBar/components/account.vue')['default']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    CdpIcon: typeof import('./../components/cdpIcon.vue')['default']
    CurrencySignText: typeof import('./../layout/headerBar/components/currencySignText.vue')['default']
    Example: typeof import('./../views/example.vue')['default']
    Headerbar: typeof import('./../layout/headerBar/headerbar.vue')['default']
    Home: typeof import('./../views/home/index.vue')['default']
    LoadingBox: typeof import('./../components/loadingBox.vue')['default']
    Login: typeof import('./../views/login.vue')['default']
    Main: typeof import('./../layout/main.vue')['default']
    PlatformGroup: typeof import('./../layout/headerBar/components/platformGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../layout/sidebar/sidebar.vue')['default']
    TopCard: typeof import('./../views/home/topCard.vue')['default']
    TotalM: typeof import('./../views/total/totalM.vue')['default']
    TotalS: typeof import('./../views/total/totalS.vue')['default']
  }
}
