/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    Account: typeof import('./../layout/headerBar/components/account.vue')['default']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AntDate: typeof import('./../components/input/antDate.vue')['default']
    AntDateRange: typeof import('./../components/input/antDateRange.vue')['default']
    AntInput: typeof import('./../components/input/antInput.vue')['default']
    AntSelect: typeof import('./../components/input/antSelect.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    CdpIcon: typeof import('./../components/CdpIcon.vue')['default']
<<<<<<< HEAD
    copy: typeof import('./../components/input/antSelect copy.vue')['default']
    CurrencySignText: typeof import('./../layout/headerBar/components/currencySignText.vue')['default']
    Headerbar: typeof import('./../layout/headerBar/headerbar.vue')['default']
    LoadingBox: typeof import('./../components/LoadingBox.vue')['default']
=======
    CurrencySignText: typeof import('./../layout/headerBar/components/currencySignText.vue')['default']
    Example: typeof import('./../views/Example.vue')['default']
    Headerbar: typeof import('./../layout/headerBar/headerbar.vue')['default']
    Home: typeof import('./../views/home/index.vue')['default']
    LoadingBox: typeof import('./../components/LoadingBox.vue')['default']
    Login: typeof import('./../views/Login.vue')['default']
>>>>>>> d38964e ([add] login page)
    Main: typeof import('./../layout/Main.vue')['default']
    PlatformGroup: typeof import('./../layout/headerBar/components/platformGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../layout/sidebar/sidebar.vue')['default']
<<<<<<< HEAD
=======
    TopCard: typeof import('./../views/home/topCard.vue')['default']
    TotalM: typeof import('./../views/Total/TotalM.vue')['default']
    TotalS: typeof import('./../views/Total/TotalS.vue')['default']
>>>>>>> d38964e ([add] login page)
  }
}
